import React, { createContext, useContext, useState, useEffect, useCallback } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Lang = "tr" | "en";

const translations: Record<Lang, Record<string, string>> = {
  tr: {
    // Tab bar
    "tab.home": "Ana Sayfa",
    "tab.services": "Servis",
    "tab.quotes": "Teklif",
    "tab.customers": "Müşteriler",
    "tab.schedule": "Plan",
    "tab.payments": "Ödemeler",
    "tab.settings": "Ayarlar",

    // Teklifler
    "qot.title": "Teklifler",
    "qot.subtitle": "Müşterilere göndereceğiniz teklifleri oluşturun ve yönetin",
    "qot.newQuote": "Yeni Teklif",
    "qot.editQuote": "Teklifi Düzenle",
    "qot.allQuotes": "Tüm Teklifler",
    "qot.confirmDelete": "{name} için bu teklifi silmek istediğinize emin misiniz?",
    "qot.pdfTitle": "Teklif Önizleme",
    "qot.downloadPdf": "PDF İndir",
    "qot.pdfDialogTitle": "Teklif PDF'i",
    "qot.date": "Tarih:",
    "qot.validUntil": "Geçerlilik:" ,
    "qot.customerInfo": "Müşteri Bilgileri",
    "qot.customerName": "Müşteri Adı",
    "qot.customerNamePlaceholder": "Müşteri adı",
    "qot.customerRequired": "Lütfen müşteri adını girin.",
    "qot.lineRequired": "En az bir ürün satırı ekleyin.",
    "qot.product": "Ürün",
    "qot.quantity": "Adet",
    "qot.unitPrice": "Birim Fiyat",
    "qot.total": "Toplam",
    "qot.noItems": "Ürün bulunmuyor",
    "qot.address": "Adres",
    "qot.addressPlaceholder": "Adres",
    "qot.phone": "Telefon",
    "qot.phonePlaceholder": "Telefon",
    "qot.email": "E-posta",
    "qot.emailPlaceholder": "E-posta",
    "qot.documentDate": "Belge Tarihi",
    "qot.datePlaceholder": "GG/AA/YYYY",
    "qot.validUntilLabel": "Geçerlilik Tarihi",
    "qot.quickValidity": "Hızlı Seçim",
    "qot.valid1Day": "1 Gün",
    "qot.valid1Week": "1 Hafta",
    "qot.valid2Week": "2 Hafta",
    "qot.valid1Month": "1 Ay",
    "qot.items": "Ürünler",
    "qot.addItem": "Ürün Ekle",
    "qot.productName": "Ürün Adı",
    "qot.productNamePlaceholder": "Ürün adı",
    "qot.details": "Detaylar",
    "qot.detailsPlaceholder": "Açıklama / detaylar",
    "qot.subtotal": "Ara Toplam",
    "qot.kdv": "KDV",
    "qot.grandTotal": "Genel Toplam",
    "qot.notes": "Notlar",
    "qot.notesPlaceholder": "Teklif notları...",
    "qot.clear": "Temizle",
    "qot.update": "Güncelle",
    "qot.selectCustomer": "Müşteri Seç",
    "qot.searchCustomer": "Müşteri ara...",
    "qot.noCustomers": "Kayıtlı müşteri bulunamadı",
    "qot.approvedBy": "Onaylayan / Yetkili",
    "qot.companyStampLabel": "Firma Kaşesi",
    "qot.companyInfo": "Firma Bilgileri",
    "qot.companyPhone": "Telefon",
    "qot.companyFax": "Fax",
    "qot.companyEmail": "E-posta",
    "qot.companyWebsite": "Web Sitesi",
    "qot.companyTax": "Vergi No",
    "qot.contactPerson": "İlgili Kişi",
    "qot.contactPersonPlaceholder": "İlgili kişi",
    "qot.subscriberNo": "Abone No",
    "qot.subscriberNoPlaceholder": "Abone no",
    "qot.fax": "Fax",
    "qot.faxPlaceholder": "Fax",
    "qot.website": "Web Sitesi",
    "qot.websitePlaceholder": "Web sitesi",
    "qot.warning": "Uyarı",
    "qot.success": "Başarılı",
    "qot.successCreated": "Teklif kaydedildi.",
    "qot.successUpdated": "Teklif güncellendi.",
    "qot.error": "Hata",
    "qot.errorSave": "Teklif kaydedilemedi.",
    "qot.errorDelete": "Teklif silinemedi.",
    "qot.errorPdfCreate": "PDF oluşturulamadı: ",
    "qot.errorPdfData": "Önizleme verisi bulunamadı.",
    "qot.showing": "gösteriliyor",
    "qot.filterAll": "Tümü",
    "qot.filterDay": "Bugün",
    "qot.filterMonth": "Bu Ay",
    "qot.filterYear": "Bu Yıl",
    "qot.filterDate": "Tarih",
    "qot.filterCustomer": "Müşteri",
    "qot.colDate": "Tarih",
    "qot.colCustomer": "Müşteri",
    "qot.colTotal": "Toplam",

    // Theme
    "theme.light": "Açık",
    "theme.dark": "Koyu",

    // Dashboard
    "dash.welcome": "Hoş Geldiniz",
    "dash.subtitle": "Size nasıl yardımcı olabiliriz?",
    "dash.services": "Servisler",
    "dash.services.desc": "Aktif servislerinizi görüntüleyin ve yönetin",
    "dash.newService": "Yeni Servis",
    "dash.manage": "Yönet",
    "dash.quotes": "Teklifler",
    "dash.quotes.desc": "Müşterilerinize göndereceğiniz teklifleri oluşturun ve yönetin",
    "dash.newQuote": "Yeni Teklif",
    "dash.customers": "Müşteriler",
    "dash.customers.desc": "Tüm müşterilerinizi görüntüleyin ve yönetin",
    "dash.noCustomers": "Kayıtlı müşteri bulunmamaktadır",
    "dash.plan": "Plan Yap",
    "dash.today": "Bugün",
    "dash.tomorrow": "Yarın",
    "dash.thisWeek": "Bu Hafta",
    "dash.noPlan": "Bu dönem için plan yok",
    "dash.paymentStatus": "ÖDEME DURUMU",
    "dash.receivedPayment": "Alınan Ödeme",
    "dash.pendingPayment": "Bekleyen Ödeme",
    "dash.estimatedTotal": "Tahmini Toplam Ödeme",
    "dash.receivedTotal": "Alınan Toplam",
    "dash.pendingTotal": "Bekleyen Toplam",
    "dash.estimatedCash": "Tahmini Kasa",
    "dash.recentServices": "SON SERVİSLER",
    "dash.noRecords": "Henüz servis kaydı yok",
    "dash.settings": "Ayarlar",
    "dash.settings.desc": "Profil ve uygulama ayarlarınızı yapılandırın",
    "dash.editProfile": "Profili Düzenle",
    "dash.settingsBtn": "Ayarlar",
    "dash.confirmRevert": "Ödemeyi Geri Al",
    "dash.confirmMarkPaid": "Ödendi Olarak İşaretle",
    "dash.confirmRevertMsg": "\"{name}\" ödemesini bekliyor olarak işaretlemek istediğinize emin misiniz?",
    "dash.confirmMarkPaidMsg": "\"{name}\" servisini ödendi olarak işaretlemek istediğinize emin misiniz?",
    "dash.planDetail": "Plan Detayı",
    "dash.date": "Tarih",
    "dash.timeDuration": "Saat & Süre",
    "dash.team": "Ekip",
    "dash.notes": "Notlar",
    "dash.goToPlan": "Plan Sayfasına Git",

    // Payments
    "pay.title": "Ödeme Yönetimi",
    "pay.subtitle": "Ödemelerinizi görüntüleyin ve yönetin",
    "pay.status": "ÖDEME DURUMU",
    "pay.receivedPayment": "Alınan Ödeme",
    "pay.pendingPayment": "Bekleyen Ödeme",
    "pay.estimatedTotal": "Tahmini Toplam Ödeme",
    "pay.receivedTotal": "Alınan Toplam",
    "pay.pendingTotal": "Bekleyen Toplam",
    "pay.estimatedCash": "Tahmini Kasa",
    "pay.list": "ÖDEME LİSTESİ",
    "pay.search": "Ara...",
    "pay.allStatus": "Tüm Durumlar",
    "pay.paid": "Ödendi",
    "pay.pending": "Bekliyor",
    "pay.all": "Tümü",
    "pay.today": "Bu Gün",
    "pay.thisWeek": "Bu Hafta",
    "pay.thisMonth": "Bu Ay",
    "pay.selectStatus": "Durum Seç",
    "pay.cancel": "İptal",
    "pay.noRecords": "Henüz servis kaydı bulunmuyor.",
    "pay.previous": "Önceki",
    "pay.next": "Sonraki",
    "pay.loading": "Yükleniyor...",
    "pay.errorLoad": "Ödeme verileri yüklenemedi.",
    "pay.errorUpdate": "Ödeme durumu güncellenemedi.",
    "pay.serviceReport": "Servis Raporu",

    // Services
    "svc.title": "Servis Yönetimi",
    "svc.subtitle": "Servis kayıtlarını oluşturun ve yönetin",
    "svc.newRecord": "Yeni Servis Kaydı",
    "svc.editRecord": "Servis Kaydını Düzenle",
    "svc.selectCustomer": "Müşteri Seç",
    "svc.clearSelection": "Seçimi Temizle",
    "svc.searchCustomer": "Müşteri ara...",
    "svc.addNewCustomer": "Yeni Müşteri Ekle",
    "svc.customerName": "Müşteri Adı",
    "svc.serviceAddress": "Servis Adresi",
    "svc.startTime": "Başlangıç",
    "svc.endTime": "Bitiş",
    "svc.customerPhone": "Müşteri Telefonu",
    "svc.internalIp": "Dahili IP",
    "svc.externalIp": "Harici IP",
    "svc.serviceServices": "Servis Hizmetleri",
    "svc.technicalServices": "Teknik Hizmetler",
    "svc.details": "Detaylar",
    "svc.serviceFee": "Servis Ücreti (₺)",
    "svc.technician": "Teknisyen",
    "svc.documentDate": "Belge Tarihi",
    "svc.update": "Güncelle",
    "svc.save": "Kaydet",
    "svc.allRecords": "Tüm Servis Kayıtları",
    "svc.showing": "kayıt gösteriliyor",
    "svc.filterAll": "Tümü",
    "svc.filterDay": "Gün",
    "svc.filterMonth": "Ay",
    "svc.filterYear": "Yıl",
    "svc.filterDate": "Tarih",
    "svc.filterDocName": "Belge Adı",
    "svc.filterCustomer": "Müşteri",
    "svc.colDate": "Tarih",
    "svc.colDocName": "Belge Adı",
    "svc.colCustomer": "Müşteri",
    "svc.colService": "Servis",
    "svc.colTemplate": "Şablon",
    "svc.allTemplates": "Tüm Şablonlar",
    "svc.noTemplate": "Şablon Yok",
    "svc.newCustomer": "Yeni Müşteri",
    "svc.companyName": "Şirket Adı",
    "svc.address": "Adres",
    "svc.email": "E-posta",
    "svc.phone": "Telefon",
    "svc.contactPerson": "Sorumlu Kişi",
    "svc.contactPhone": "Sorumlu Telefon",
    "svc.cancel": "İptal",
    "svc.customerSignature": "Müşteri İmzası",
    "svc.confirmSave": "Bu servis kaydını oluşturmak istediğinize emin misiniz?",
    "svc.confirmUpdate": "Bu servis kaydını güncellemek istediğinize emin misiniz?",
    "svc.confirmDelete": "\"{name}\" servis kaydını silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
    "svc.delete": "Sil",
    "svc.signHere": "Lütfen bu alana imzanızı atınız",
    "svc.clear": "Temizle",
    "svc.successCreated": "Servis kaydı oluşturuldu.",
    "svc.successUpdated": "Servis kaydı güncellendi.",
    "svc.errorSave": "Kayıt sırasında bir sorun oluştu.",
    "svc.errorUpdate": "Güncelleme sırasında bir sorun oluştu.",
    "svc.errorDelete": "Servis kaydı silinemedi.",
    "svc.errorRequired": "Müşteri adı zorunludur.",
    "svc.errorTimeEqual": "Başlangıç ve bitiş saati aynı olamaz.",
    "svc.errorCompanyRequired": "Şirket adı zorunludur.",
    "svc.errorCustomerAdd": "Müşteri eklenirken bir sorun oluştu.",
    "svc.noSignature": "Servis kaydı oluşturmak veya güncellemek için lütfen profil sayfasından kendi imzanızı kaydedin.",
    "svc.warning": "Uyarı",
    "svc.error": "Hata",
    "svc.success": "Başarılı",
    "svc.share": "Paylaş",
    "svc.shareTitle": "Servis Kaydı",
    "svc.shareOther": "Diğer",
    "svc.shareError": "Paylaşım sırasında bir hata oluştu.",
    "svc.sharePhoneTitle": "Numara Seç",
    "svc.phoneService": "Servis kaydı telefonu",
    "svc.phoneMain": "Ana telefon",
    "svc.phoneContact": "İrtibat telefonu",
    "svc.phoneNotFound": "Bu kayıt için telefon numarası bulunamadı.",

    // Customers
    "cst.title": "Müşteri Yönetimi",
    "cst.subtitle": "Müşterilerinizi görüntüleyin ve yönetin",
    "cst.newCustomer": "Yeni Müşteri Ekle",
    "cst.editCustomer": "Müşteri Düzenle",
    "cst.allCustomers": "Tüm Müşteriler",
    "cst.records": "kayıt",
    "cst.search": "Müşteri ara...",
    "cst.noCustomers": "Müşteri bulunamadı.",
    "cst.loading": "Yükleniyor...",
    "cst.previous": "Önceki",
    "cst.next": "Sonraki",
    "cst.customerInfo": "Müşteri Bilgileri",
    "cst.contactPerson": "Sorumlu Kişi",
    "cst.phone": "Telefon",
    "cst.contactPhone": "Sorumlu Telefon",
    "cst.fax": "Fax",
    "cst.website": "Web Sitesi",
    "cst.email": "E-posta",
    "cst.address": "Adres",
    "cst.edit": "Düzenle",
    "cst.close": "Kapat",
    "cst.companyName": "Şirket Adı",
    "cst.subscriberNo": "Abone No",
    "cst.errorLoad": "Müşteriler yüklenirken bir sorun oluştu.",
    "cst.errorRequired": "Şirket adı gerekli",
    "cst.errorSave": "İşlem sırasında bir sorun oluştu.",
    "cst.errorDelete": "Silme işleminde bir sorun oluştu.",
    "cst.errorEdit": "Müşteri bilgileri yüklenirken bir sorun oluştu.",
    "cst.successAdd": "Müşteri eklendi.",
    "cst.successUpdate": "Müşteri güncellendi.",
    "cst.successDelete": "Müşteri silindi.",
    "cst.confirmDelete": "Silmek istediğinize emin misiniz?",
    "cst.delete": "Sil",

    // Schedule
    "sch.title": "Plan Yönetimi",
    "sch.subtitle": "Ekiplerinizi ve servis planlarınızı yönetin",
    "sch.day": "Gün",
    "sch.week": "Hafta",
    "sch.month": "Ay",
    "sch.allTeams": "Tüm Ekipler",
    "sch.newPlan": "Yeni Plan",
    "sch.planList": "Plan Listesi",
    "sch.teams": "Ekipler",
    "sch.noTeams": "Ekip bulunmamaktadır",
    "sch.newTeam": "Yeni Ekip",
    "sch.noPlanToday": "Bu gün için plan yok",
    "sch.noPlanWeek": "Bu hafta için plan yok",
    "sch.noPlanMonth": "Bu ay için plan yok",
    "sch.noPlanFound": "Plan bulunamadı",
    "sch.past": "Geçmiş",
    "sch.teamName": "Ekip Adı",
    "sch.teamLeader": "Ekip Lideri",
    "sch.selectLeader": "Lider seçin...",
    "sch.personnel": "Personeller",
    "sch.selectPersonnel": "Personel seçin...",
    "sch.personnelSelected": "personel seçildi",
    "sch.cancel": "İptal",
    "sch.add": "Ekle",
    "sch.assignments": "atama",
    "sch.personnelCount": "Personel",
    "sch.teamDelete": "Ekibi Sil",
    "sch.teamDeleteMsg": "Bu ekibi silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
    "sch.yesDelete": "Evet, Sil",
    "sch.addPersonnel": "Personel Ekle",
    "sch.searchPersonnel": "Personel ara...",
    "sch.noResults": "Sonuç bulunamadı",
    "sch.noPersonnelLeft": "Eklenebilecek personel kalmadı",
    "sch.removePersonnel": "Personel Çıkar",
    "sch.removePersonnelMsg": "Çıkarmak istediğiniz personeli seçin:",
    "sch.leaderWarning": "Lider: {leader} — lider çıkarılamaz, sadece üyeler seçilebilir.",
    "sch.noPersonnelToRemove": "Ekipte çıkarılacak personel yok",
    "sch.removeSelected": "Kişiyi Çıkar",
    "sch.removeDefault": "Seçilenleri Çıkar",
    "sch.newAppointment": "Servis Atama",
    "sch.updateAppointment": "Planı Güncelle",
    "sch.customer": "Müşteri",
    "sch.selectCustomer": "Müşteri seçin...",
    "sch.date": "Tarih",
    "sch.time": "Saat",
    "sch.duration": "Süre",
    "sch.selectTeam": "Ekip Seç",
    "sch.serviceType": "Servis Türü",
    "sch.notes": "Notlar",
    "sch.notesPlaceholder": "Servis notları...",
    "sch.assign": "Atama Yap",
    "sch.update": "Güncelle",
    "sch.save": "Kaydet",
    "sch.planDelete": "Planı Sil",
    "sch.planDeleteMsg": "Bu planı silmek istediğinize emin misiniz?",
    "sch.planDetail": "Plan Detayı",
    "sch.timeDuration": "Saat & Süre",
    "sch.team": "Ekip",
    "sch.loading": "Yükleniyor...",
    "sch.errorTeamRequired": "Ekip adı ve lider zorunludur.",
    "sch.errorTeamAdd": "Ekip eklenemedi.",
    "sch.errorTeamDelete": "Ekip silinemedi.",
    "sch.errorPersonnelAdd": "Personel eklenemedi.",
    "sch.errorPersonnelRemove": "Personel çıkarılamadı.",
    "sch.errorCustomerRequired": "Müşteri seçimi zorunludur.",
    "sch.errorInvalidTime": "Geçerli saat girin (HH:MM).",
    "sch.errorTimeRange": "Saat 08:00 - 23:00 arasında olmalıdır.",
    "sch.errorConflict": "Çakışma",
    "sch.errorConflictMsg": "\"{name}\" planı {time} - {duration} arasında bu ekip için zaten tanımlı. Farklı bir saat seçin.",
    "sch.errorSave": "İşlem başarısız.",
    "sch.errorDrag": "Plan taşınamadı.",
    "sch.errorLoad": "Veriler yüklenirken bir hata oluştu.",
    "sch.errorSelectPersonnel": "Lütfen en az bir personel seçin.",
    "sch.tempCustomer": "Geçici müşteri adı girin...",
    "sch.selectPersonnelToRemove": "Personel seçin",
    "sch.more": "daha",

    // Profile
    "prf.title": "Profil",
    "prf.info": "Bilgiler",
    "prf.name": "Ad Soyad",
    "prf.email": "E-posta",
    "prf.phone": "Telefon",
    "prf.role": "Rol",
    "prf.signature": "İmza",
    "prf.addSignature": "İmza Eklemek İçin Tıklayın",
    "prf.mySignature": "İmzam",
    "prf.signHere": "Lütfen bu alana imzanızı atınız",
    "prf.clear": "Temizle",
    "prf.save": "Kaydet",
    "prf.adminPrivileges": "Admin Yetkileri",
    "prf.companyInfo": "Kurumsal Bilgiler",
    "prf.invitationCode": "Davet Kodu",
    "prf.invitationHint": "Bu kodu paylaşıp çalışan kaydı yapabilirsiniz.",
    "prf.address": "Adres",
    "prf.companyPhone": "Telefon",
    "prf.companyEmail": "E-posta",
    "prf.companyFax": "Fax",
    "prf.companyWebsite": "Web Sitesi",
    "prf.taxNumber": "Vergi Numarası",
    "prf.logo": "Logo",
    "prf.logoSelected": "Logo seçildi",
    "prf.logoSelect": "Logo seçin...",
    "prf.stamp": "Kaşe",
    "prf.stampSelected": "Kaşe seçildi",
    "prf.stampSelect": "Kaşe görseli seçin...",
    "prf.logout": "Çıkış Yap",
    "prf.deleteAccount": "Hesabı Sil",
    "prf.deleteAccountConfirm": "Hesabınızı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    "prf.errorDeleteAccount": "Hesap silinirken bir hata oluştu.",
    "prf.loading": "Yükleniyor...",
    "prf.error": "Bir hata oluştu",
    "prf.retry": "Tekrar Dene",
    "prf.nameEmpty": "Ad Soyad boş bırakılamaz.",
    "prf.companyNameEmpty": "Şirket adı boş bırakılamaz.",
    "prf.successUser": "Profil bilgileriniz güncellendi.",
    "prf.successCompany": "Kurumsal bilgiler güncellendi.",
    "prf.successSignature": "İmzanız kaydedildi.",
    "prf.errorUser": "Güncelleme başarısız.",
    "prf.errorCompany": "Güncelleme başarısız.",
    "prf.errorSignature": "İmza kaydedilemedi.",
    "prf.copied": "Kopyalandı",
    "prf.copiedMsg": "Davet kodu panoya kopyalandı:\n{code}",
    "prf.signRequired": "Lütfen imza atın.",

    // Settings
    "set.title": "Ayarlar",
    "set.subtitle": "Profil ve uygulama ayarlarınızı yapılandırın",
    "set.platform": "Servis Takip Platformu",
    "set.profileInfo": "Profil Bilgileri",
    "set.language": "Dil",
    "set.turkish": "Türkçe",
    "set.english": "English",
    "set.privacy": "Gizlilik",
    "set.help": "Yardım",
    "set.version": "Sürüm",
    "set.logout": "Çıkış Yap",

    // Service form templates
    "tpl.menuLabel": "Servis Formu Şablonları",
    "tpl.menuRight": "Düzenle",
    "tpl.title": "Servis Formu Şablonları",
    "tpl.subtitle": "Servis kaydı formunun düzenini özelleştirin",
    "tpl.formLabel": "Form Şablonu",
    "tpl.manage": "Yönet",
    "tpl.create": "Yeni Şablon",
    "tpl.createTitle": "Yeni Şablon Oluştur",
    "tpl.createSource": "Şablon içeriği",
    "tpl.createCopy": "Seçili şablondan kopyala",
    "tpl.createBlank": "Varsayılan (boş) şablonla başla",
    "tpl.newTemplateName": "Yeni Şablon",
    "tpl.created": "Şablon Oluşturuldu",
    "tpl.createdMsg": "Yeni şablon oluşturuldu. Düzenleyip kaydedebilirsiniz.",
    "tpl.saved": "Şablon kaydedildi.",
    "tpl.applyTitle": "Kayıtlara Uygula",
    "tpl.applyMessage": "{count} kayıt bu şablonla kaydedilmiş. Değişiklikler bu kayıtların PDF'lerine de uygulansın mı?",
    "tpl.applyYes": "Evet, Uygula",
    "tpl.applyNo": "Hayır",
    "tpl.applyCancel": "İptal",
    "tpl.operationCancelled": "İşlem iptal edildi. Şablon önceki haline geri alındı.",
    "tpl.recordsUpdated": "{count} kayıt güncellendi.",
    "tpl.errorApply": "Kayıtlara uygulanırken hata oluştu.",
    "tpl.name": "Şablon Adı",
    "tpl.namePlaceholder": "Şablon adı girin",
    "tpl.setDefault": "Varsayılan Yap",
    "tpl.discard": "Değişiklikleri İptal Et",
    "tpl.fieldsSection": "Form Alanları",
    "tpl.fieldsHint": "Alanları açıp kapatın, sıralayın veya adlarını değiştirin.",
    "tpl.groupsSection": "Seçenek Grupları",
    "tpl.groupsHint": "Grupları ve seçenekleri ekleyin, düzenleyin veya kaldırın.",
    "tpl.addOption": "Seçenek Ekle",
    "tpl.addGroup": "Grup Ekle",
    "tpl.editLabel": "Etiketi Düzenle",
    "tpl.labelTr": "Türkçe Etiket",
    "tpl.labelEn": "İngilizce Etiket",
    "tpl.label": "Etiket",
    "tpl.autoTranslateHint": "Diğer dildeki karşılığı otomatik çevrilecektir.",
    "tpl.confirmDelete": "Bu şablonu silmek istediğinize emin misiniz?",
    "tpl.noAccess": "Bu sayfayı görüntülemek için admin yetkisi gerekir.",
    "tpl.newGroupTr": "Yeni Grup",
    "tpl.newGroupEn": "New Group",
    "tpl.newOptionTr": "Yeni Seçenek",
    "tpl.newOptionEn": "New Option",
    "tpl.errorSave": "Şablon kaydedilemedi.",
    "tpl.errorDelete": "Şablon silinemedi.",
    "tpl.errorDefault": "Varsayılan şablon ayarlanamadı.",
    "tpl.addField": "Alan Ekle",
    "tpl.newFieldTr": "Yeni Alan",
    "tpl.newFieldEn": "New Field",
    "tpl.inputType": "İçerik Türü",
    "tpl.fieldOptions": "Seçenekler",
    "tpl.typeText": "Metin",
    "tpl.typeNumber": "Sayı",
    "tpl.typeTextarea": "Çok Satırlı",
    "tpl.typeSelect": "Select",
    "tpl.typeRadio": "Radio",
    "tpl.typeMulti": "Çoklu Seçim",

    // Login
    "login.subtitle": "Servis Takip Platformu",
    "login.email": "E-posta",
    "login.password": "Şifre",
    "login.forgotPassword": "Şifremi Unuttum",
    "login.login": "Giriş Yap",
    "login.noAccount": "Hesabın yok mu? ",
    "login.register": "Kayıt Ol",
    "login.errorEmail": "E-posta alanı boş olamaz.",
    "login.errorPassword": "Şifre alanı boş olamaz.",
    "login.errorLogin": "Giriş başarısız. Lütfen bilgilerinizi kontrol edin.",
    "login.error": "Hata",

    // Forgot Password
    "forgot.subtitle": "Şifremi Unuttum",
    "forgot.description": "E-posta adresinizi girin, size şifre sıfırlama kodu gönderelim.",
    "forgot.email": "E-posta",
    "forgot.sendCode": "Kodu Gönder",
    "forgot.backToLogin": "Giriş sayfasına dön",
    "forgot.successTitle": "Kodu Gönderildi",
    "forgot.successMessage": "Şifre sıfırlama kodu e-posta adresinize gönderildi.",
    "forgot.errorEmail": "E-posta alanı boş olamaz.",
    "forgot.errorGeneric": "Şifre sıfırlama isteği sırasında bir hata oluştu.",

    // Reset Password
    "reset.title": "Şifre Sıfırlama",
    "reset.subtitle": "E-posta adresinize gönderilen 6 haneli kodu ve yeni şifrenizi girin",
    "reset.emailSent": "Sıfırlama kodu {email} adresine gönderildi",
    "reset.newPassword": "Yeni Şifre",
    "reset.confirmPassword": "Şifre Tekrar",
    "reset.resetButton": "Şifreyi Sıfırla",
    "reset.success": "Şifreniz başarıyla sıfırlandı!",
    "reset.errorEmptyCode": "Doğrulama kodu boş olamaz.",
    "reset.errorEmptyPassword": "Yeni şifre boş olamaz.",
    "reset.errorPasswordLength": "Şifre en az 6 karakter olmalıdır.",
    "reset.errorPasswordMatch": "Şifreler eşleşmiyor.",
    "reset.errorGeneric": "Şifre sıfırlama sırasında bir hata oluştu.",

    // Common
    "common.confirm": "Onayla",
    "common.cancel": "İptal",
    "common.ok": "Tamam",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.close": "Kapat",
    "common.loading": "Yükleniyor...",
    "common.error": "Hata",
    "common.success": "Başarılı",
    "common.warning": "Uyarı",
    "common.service": "Servis",

    // Privacy
    "privacy.title": "Gizlilik Politikası",
    "privacy.dataStorage": "Veri Saklama & Güvenlik",
    "privacy.dataStorageDesc": "Verileriniz SSL ile şifrelenerek saklanır. Sunucularımız Türkiye'de barındırılmaktadır. Düzenli güvenlik denetimleri yapılır.",
    "privacy.personalData": "Kişisel Veri Kullanımı",
    "privacy.personalDataDesc": "Ad, soyad, e-posta, telefon bilgileriniz yalnızca servis yönetimi için kullanılır. İmza verileriniz yalnızca servis formlarında kullanılır. Üçüncü taraflarla paylaşılmaz.",
    "privacy.dataSharing": "Veri Paylaşımı",
    "privacy.dataSharingDesc": "Müşteri bilgileriniz yalnızca yetkili personel tarafından görülebilir. Yasal zorunluluk olmadıkça verileriniz paylaşılmaz.",
    "privacy.retention": "Veri Saklama Süresi",
    "privacy.retentionDesc": "Hesabınız aktif olduğu sürece verileriniz saklanır. Hesap silindiğinde tüm veriler 30 gün içinde kalıcı olarak silinir.",
    "privacy.accountDeletion": "Hesap Silme",
    "privacy.accountDeletionDesc": "Hesabınızı silmek istiyorsanız, Ayarlar menüsünden çıkış yaparak veya destek ekibimize başvurarak hesabınızı kapatabilirsiniz. Bu işlem geri alınamaz.",
    "privacy.notifications": "İletişim Tercihleri",
    "privacy.notificationsDesc": "Bildirim tercihlerinizi ayarlayabilirsiniz. Pazarlama e-postalarını kapatabilirsiniz.",
    "privacy.contact": "Gizlilik ile ilgili sorularınız için bizimle iletişime geçin.",
    "privacy.email": "gizlilik@sirket.com",

    // Month names (for calendar)
    "month.january": "Ocak",
    "month.february": "Şubat",
    "month.march": "Mart",
    "month.april": "Nisan",
    "month.may": "Mayıs",
    "month.june": "Haziran",
    "month.july": "Temmuz",
    "month.august": "Ağustos",
    "month.september": "Eylül",
    "month.october": "Ekim",
    "month.november": "Kasım",
    "month.december": "Aralık",

    // Day names
    "day.monday": "Pazartesi",
    "day.tuesday": "Salı",
    "day.wednesday": "Çarşamba",
    "day.thursday": "Perşembe",
    "day.friday": "Cuma",
    "day.saturday": "Cumartesi",
    "day.sunday": "Pazar",

    // Duration
    "dur.30min": "30 dk",
    "dur.1hour": "1 saat",
    "dur.1.5hour": "1.5 saat",
    "dur.2hour": "2 saat",
    "dur.custom": "Özel Süre (saat)",

    // Days short
    "dayShort.mon": "Pzt",
    "dayShort.tue": "Sal",
    "dayShort.wed": "Çar",
    "dayShort.thu": "Per",
    "dayShort.fri": "Cum",
    "dayShort.sat": "Cmt",
    "dayShort.sun": "Paz",

    // Service lists
    "svc.list.alarm": "Alarm",
    "svc.list.fire": "Yangın",
    "svc.list.cctv": "CCTV",
    "svc.list.ahm": "AHM Bağlantısı",
    "svc.list.wiring": "Kablolama",
    "svc.list.assembly": "Montaj",
    "svc.list.commissioning": "Devreye Alma Eğitimi",
    "svc.list.docCheck": "Belge Kontrolü",
    "svc.list.testing": "Test Sinyal Programlama",
    "svc.list.maintenance": "Bakım",
    "svc.list.repair": "Arıza",
    "svc.list.training": "Devreye Alma",

    // Technical list
    "svc.tech.ahmSignal": "AHM Sinyal Kontrolü",
    "svc.tech.drill": "Eğitim ve Tatbikat",
    "svc.tech.dovr": "DOVR Kayıt Kontrol",
    "svc.tech.remote": "Uzak Erişim",
    "svc.tech.backup": "Kayıt ve Yedekleme Eğitimi",
    "svc.tech.cameraClarity": "Kameralara Netlik ve Yön Ayarı",
    "svc.tech.signalTest": "Test Sinyal Programlama",
    "svc.tech.battery": "Akü Ömrü Kontrolü",
    "svc.tech.wirelessPil": "Kablosuz Dedektör Pil Kontrolü",
    "svc.tech.gprs": "GPRS Bağlantısı",

    // Service form extras
    "svc.serviceForm": "Servis Formu",
    "svc.serviceInfo": "Servis Bilgileri",
    "svc.feeLabel": "Ücret:",
    "svc.technical": "Teknik:",
    "svc.services": "Servisler:",
    "svc.notSpecified": "Belirtilmemiş",
    "svc.confirmCreate": "Bu servis kaydını oluşturmak istediğinize emin misiniz?",
    "svc.signatureRequired": "İmza Gerekli",
    "svc.signatureWarning": "Lütfen imza atın.",
    "svc.goToProfile": "Profil Sayfasına Git",
    "svc.pdfDialogTitle": "Servis Formu.pdf",
    "svc.errorPdfData": "PDF verisi bulunamadı.",
    "svc.errorPopup": "Yeni pencere açılamadı. Lütfen pop-up engelleyiciyi kontrol edin.",
    "svc.errorPdfCreate": "PDF oluşturulurken bir sorun oluştu: ",
    "svc.infoPdf": "PDF oluşturma özelliği yeniden düzenleniyor...",
    "svc.downloadPdf": "PDF İndir",
    "svc.companyNamePlaceholder": "Şirket adı",
    "svc.subscriberNo": "Abone No",
    "svc.customerNamePlaceholder": "Müşteri adını girin",
    "svc.serviceAddressPlaceholder": "Servis adresini girin veya seçin",
    "svc.phonePlaceholder": "Telefon numarası",
    "svc.contactPersonPlaceholder": "Sorumlu kişi",
    "svc.contactPhonePlaceholder": "Sorumlu telefon",
    "svc.internalIpPlaceholder": "Dahili IP",
    "svc.externalIpPlaceholder": "Harici IP",
    "svc.detailsPlaceholder": "Ek detaylar veya notlar",
    "svc.datePlaceholder": "Tarih giriniz (GG/AA/YYYY)",
    "svc.documentName": "Belge Adı",

    // Dashboard extras
    "dash.service": "Servis",
    "dash.paid": "Ödendi",
    "dash.pending": "Bekliyor",

    // Schedule extras
    "sch.servicePlan": "servis planı",
    "sch.leader": "Lider:",
    "sch.serviceTypes.alarm": "Alarm",
    "sch.serviceTypes.fire": "Yangın",
    "sch.serviceTypes.cctv": "CCTV",
    "sch.serviceTypes.assembly": "Montaj",
    "sch.serviceTypes.wiring": "Kablolama",
    "sch.serviceTypes.commissioning": "Devreye Alma",
    "sch.serviceTypes.maintenance": "Bakım",
    "sch.serviceTypes.repair": "Arıza",

    // Register
    "reg.title": "Yeni hesap oluşturun",
    "reg.inviteCode": "Davet Kodu",
    "reg.inviteCodePlaceholder": "Admin veya davet kodunu girin",
    "reg.inviteHint": "\"ADMIN-XXX\" ile admin, \"INVITE-XXX\" ile çalışan kaydı yapabilirsiniz.",
    "reg.fullName": "Ad Soyad",
    "reg.email": "E-posta",
    "reg.phone": "Telefon",
    "reg.password": "Şifre",
    "reg.confirmPassword": "Şifre Tekrar",
    "reg.register": "Kaydol",
    "reg.hasAccount": "Zaten hesabınız var mı? ",
    "reg.login": "Giriş Yap",
    "reg.errorInviteCode": "Davet kodu boş olamaz.",
    "reg.errorName": "Ad Soyad alanı boş olamaz.",
    "reg.errorEmail": "Geçerli bir e-posta adresi girin.",
    "reg.errorPhone": "Telefon en az 10 haneli olmalıdır.",
    "reg.errorPassword": "Şifre en az 6 karakter olmalıdır.",
    "reg.errorPasswordMatch": "Şifreler eşleşmiyor.",
    "reg.errorRegister": "Kayıt başarısız. Lütfen tekrar deneyin.",

    // Email Verification
    "verify.title": "E-posta Doğrulama",
    "verify.subtitle": "E-posta adresinize gönderilen 6 haneli doğrulama kodunu girin",
    "verify.emailSent": "Doğrulama kodu {email} adresine gönderildi",
    "verify.codePlaceholder": "Doğrulama Kodu",
    "verify.verify": "Doğrula",
    "verify.resend": "Kodu Tekrar Gönder",
    "verify.resendIn": "{seconds} saniye içinde tekrar gönderebilirsiniz",
    "verify.success": "E-posta başarıyla doğrulandı!",
    "verify.errorEmpty": "Doğrulama kodu boş olamaz.",
    "verify.errorInvalid": "Geçersiz doğrulama kodu.",
    "verify.errorExpired": "Doğrulama kodunun süresi dolmuş. Yeni bir kod isteyin.",
    "verify.errorGeneric": "Doğrulama sırasında bir hata oluştu.",
    "verify.backToLogin": "Giriş sayfasına dön",
    "verify.pasteCode": "Kodu Yapıştır",
    "verify.codeCopied": "Kodu panoya kopyalandı!",

    // Complete CP Profile
    "cp.title": "Kurumsal Bilgileri Tamamlayın",
    "cp.subtitle": "Şirket bilgilerinizi girerek hesabınızı tamamlayın",
    "cp.logo": "Logo",
    "cp.logoHint": "Logoya tıklayarak değiştirin",
    "cp.companyName": "Şirket Adı",
    "cp.companyNamePlaceholder": "Şirket adı",
    "cp.address": "Adres",
    "cp.companyAddressPlaceholder": "Şirket adresi",
    "cp.phone": "Telefon",
    "cp.taxNumber": "Vergi Numarası",
    "cp.email": "E-posta",
    "cp.complete": "Tamamla",
    "cp.errorGeneric": "Bir sorun oluştu. Lütfen tekrar deneyin.",

    // MapSelector
    "map.selectAddress": "Adres Seç",
    "map.currentLocation": "Mevcut Konumumu Al",
    "map.gpsHint": "GPS ile konumunuzu kullanın",
    "map.selectFromMap": "Haritadan Seç",
    "map.googleMapsHint": "Google Maps'te adres belirleyin",
    "map.mapHint": "Harita üzerinde nokta belirleyin",
    "map.permissionRequired": "İzin Gerekli",
    "map.permissionDenied": "Konum izni verilmedi.",
    "map.errorLocation": "Konum alınamadı. Tarayıcı konum iznini kontrol edin.",
    "map.errorLocationMobile": "Konum alınamadı. Lütfen GPS ve internet bağlantınızı kontrol edin.",

    // PDF
    "pdf.title": "SERVİS TESLİM FORMU",
    "pdf.date": "Tarih:",
    "pdf.customerInfo": "MÜŞTERİ BİLGİLERİ",
    "pdf.customerName": "Müşteri Adı:",
    "pdf.address": "Adres:",
    "pdf.phone": "Telefon:",
    "pdf.email": "E-posta:",
    "pdf.subscriberNo": "Abone No:",
    "pdf.serviceDetails": "SERVİS DETAYLARI",
    "pdf.responsiblePersonnel": "Sorumlu Personel:",
    "pdf.startTime": "Başlama Saati:",
    "pdf.endTime": "Bitiş Saati:",
    "pdf.phoneNumber": "Telefon Numarası:",
    "pdf.serviceServices": "SERVİS HİZMETLERİ",
    "pdf.technicalServices": "TEKNİK HİZMETLER",
    "pdf.detailsNotes": "DETAYLAR / NOTLAR",
    "pdf.additionalInfo": "EK BİLGİLER",
    "pdf.serviceFee": "SERVİS BEDELİ",
    "pdf.serviceFeeLine": "Servis Bedeli: {amount} + KDV",
    "pdf.freeService": "Ücretsiz Servis",
    "pdf.customerSignatureLabel": "Müşteri Adı & Soyadı / İmza",
    "pdf.technicianSignatureLabel": "Teknisyen Adı & Soyadı / İmza",
    "pdf.companyNameLabel": "1D GÜVENLİK VE İLETİŞİM SİSTEMLERİ TİCARET LTD. ŞTİ.",
    "pdf.companyAddressLabel": "Goncalar Mah. Ali Alp Böke Cad. No: 150 C Karşıyaka - İZMİR",
    "pdf.privacyNoteTitle": "GİZLİLİK NOTU (KVKK)",
    "pdf.privacyNoteBody": "Bu belge, 6698 sayılı KVKK kapsamında gizli olup, yalnızca ilgili müşteri içindir. Yetkisiz paylaşımı yasaktır.",

    // Profile extra
    "prf.errorLoad": "Profil bilgileri yüklenemedi.",

    // Auth extras
    "auth.errorToken": "Token alınamadı. Lütfen tekrar deneyin.",
    "auth.errorTokenSave": "Token kaydedilemedi. Lütfen tekrar deneyin.",
    "auth.errorRegisterToken": "Kayıt sonrası token alınamadı.",

    // Common extras
    "common.info": "Bilgi",
    "common.all": "Tümü",
    "common.day": "Gün",
    "common.month": "Ay",
    "common.year": "Yıl",
    "common.date": "Tarih",
    "common.customer": "Müşteri",
    "common.address": "Adres",
    "common.email": "E-posta",
    "common.phone": "Telefon",
    "common.password": "Şifre",
    "common.clear": "Temizle",
  },

  en: {
    // Tab bar
    "tab.home": "Home",
    "tab.services": "Services",
    "tab.quotes": "Quotes",
    "tab.customers": "Customers",
    "tab.schedule": "Schedule",
    "tab.payments": "Payments",
    "tab.settings": "Settings",

    // Quotes
    "qot.title": "Quotes",
    "qot.subtitle": "Create and manage quotes to send to customers",
    "qot.newQuote": "New Quote",
    "qot.editQuote": "Edit Quote",
    "qot.allQuotes": "All Quotes",
    "qot.confirmDelete": "Are you sure you want to delete this quote for {name}?",
    "qot.pdfTitle": "Quote Preview",
    "qot.downloadPdf": "Download PDF",
    "qot.pdfDialogTitle": "Quote PDF",
    "qot.date": "Date:",
    "qot.validUntil": "Valid until:" ,
    "qot.customerInfo": "Customer Information",
    "qot.customerName": "Customer Name",
    "qot.customerNamePlaceholder": "Customer name",
    "qot.customerRequired": "Please enter a customer name.",
    "qot.lineRequired": "Add at least one product line.",
    "qot.product": "Product",
    "qot.quantity": "Qty",
    "qot.unitPrice": "Unit Price",
    "qot.total": "Total",
    "qot.noItems": "No items",
    "qot.address": "Address",
    "qot.addressPlaceholder": "Address",
    "qot.phone": "Phone",
    "qot.phonePlaceholder": "Phone",
    "qot.email": "Email",
    "qot.emailPlaceholder": "Email",
    "qot.documentDate": "Document Date",
    "qot.datePlaceholder": "DD/MM/YYYY",
    "qot.validUntilLabel": "Valid Until",
    "qot.quickValidity": "Quick Select",
    "qot.valid1Day": "1 Day",
    "qot.valid1Week": "1 Week",
    "qot.valid2Week": "2 Weeks",
    "qot.valid1Month": "1 Month",
    "qot.items": "Items",
    "qot.addItem": "Add Item",
    "qot.productName": "Product Name",
    "qot.productNamePlaceholder": "Product name",
    "qot.details": "Details",
    "qot.detailsPlaceholder": "Description / details",
    "qot.subtotal": "Subtotal",
    "qot.kdv": "VAT",
    "qot.grandTotal": "Grand Total",
    "qot.notes": "Notes",
    "qot.notesPlaceholder": "Quote notes...",
    "qot.clear": "Clear",
    "qot.update": "Update",
    "qot.selectCustomer": "Select Customer",
    "qot.searchCustomer": "Search customer...",
    "qot.noCustomers": "No customers found",
    "qot.approvedBy": "Approved by",
    "qot.companyStampLabel": "Company Stamp",
    "qot.companyInfo": "Company Info",
    "qot.companyPhone": "Phone",
    "qot.companyFax": "Fax",
    "qot.companyEmail": "Email",
    "qot.companyWebsite": "Website",
    "qot.companyTax": "Tax No",
    "qot.contactPerson": "Contact Person",
    "qot.contactPersonPlaceholder": "Contact person",
    "qot.subscriberNo": "Subscriber No",
    "qot.subscriberNoPlaceholder": "Subscriber no",
    "qot.fax": "Fax",
    "qot.faxPlaceholder": "Fax",
    "qot.website": "Website",
    "qot.websitePlaceholder": "Website",
    "qot.warning": "Warning",
    "qot.success": "Success",
    "qot.successCreated": "Quote saved.",
    "qot.successUpdated": "Quote updated.",
    "qot.error": "Error",
    "qot.errorSave": "Could not save quote.",
    "qot.errorDelete": "Could not delete quote.",
    "qot.errorPdfCreate": "Could not generate PDF: ",
    "qot.errorPdfData": "Preview data not found.",
    "qot.showing": "showing",
    "qot.filterAll": "All",
    "qot.filterDay": "Today",
    "qot.filterMonth": "This Month",
    "qot.filterYear": "This Year",
    "qot.filterDate": "Date",
    "qot.filterCustomer": "Customer",
    "qot.colDate": "Date",
    "qot.colCustomer": "Customer",
    "qot.colTotal": "Total",

    // Theme
    "theme.light": "Light",
    "theme.dark": "Dark",

    // Dashboard
    "dash.welcome": "Welcome",
    "dash.subtitle": "How can we help you?",
    "dash.services": "Services",
    "dash.services.desc": "View and manage your active services",
    "dash.newService": "New Service",
    "dash.manage": "Manage",
    "dash.quotes": "Quotes",
    "dash.quotes.desc": "Create and manage quotes to send your customers",
    "dash.newQuote": "New Quote",
    "dash.customers": "Customers",
    "dash.customers.desc": "View and manage all your customers",
    "dash.noCustomers": "No registered customers found",
    "dash.plan": "Plan",
    "dash.today": "Today",
    "dash.tomorrow": "Tomorrow",
    "dash.thisWeek": "This Week",
    "dash.noPlan": "No plans for this period",
    "dash.paymentStatus": "PAYMENT STATUS",
    "dash.receivedPayment": "Received Payment",
    "dash.pendingPayment": "Pending Payment",
    "dash.estimatedTotal": "Estimated Total Payment",
    "dash.receivedTotal": "Total Received",
    "dash.pendingTotal": "Total Pending",
    "dash.estimatedCash": "Estimated Cash",
    "dash.recentServices": "RECENT SERVICES",
    "dash.noRecords": "No service records yet",
    "dash.settings": "Settings",
    "dash.settings.desc": "Configure your profile and app settings",
    "dash.editProfile": "Edit Profile",
    "dash.settingsBtn": "Settings",
    "dash.confirmRevert": "Revert Payment",
    "dash.confirmMarkPaid": "Mark as Paid",
    "dash.confirmRevertMsg": "Are you sure you want to mark \"{name}\" payment as pending?",
    "dash.confirmMarkPaidMsg": "Are you sure you want to mark \"{name}\" service as paid?",
    "dash.planDetail": "Plan Detail",
    "dash.date": "Date",
    "dash.timeDuration": "Time & Duration",
    "dash.team": "Team",
    "dash.notes": "Notes",
    "dash.goToPlan": "Go to Plan Page",

    // Payments
    "pay.title": "Payment Management",
    "pay.subtitle": "View and manage your payments",
    "pay.status": "PAYMENT STATUS",
    "pay.receivedPayment": "Received Payment",
    "pay.pendingPayment": "Pending Payment",
    "pay.estimatedTotal": "Estimated Total Payment",
    "pay.receivedTotal": "Total Received",
    "pay.pendingTotal": "Total Pending",
    "pay.estimatedCash": "Estimated Cash",
    "pay.list": "PAYMENT LIST",
    "pay.search": "Search...",
    "pay.allStatus": "All Status",
    "pay.paid": "Paid",
    "pay.pending": "Pending",
    "pay.all": "All",
    "pay.today": "Today",
    "pay.thisWeek": "This Week",
    "pay.thisMonth": "This Month",
    "pay.selectStatus": "Select Status",
    "pay.cancel": "Cancel",
    "pay.noRecords": "No service records found yet.",
    "pay.previous": "Previous",
    "pay.next": "Next",
    "pay.loading": "Loading...",
    "pay.errorLoad": "Could not load payment data.",
    "pay.errorUpdate": "Could not update payment status.",
    "pay.serviceReport": "Service Report",

    // Services
    "svc.title": "Service Management",
    "svc.subtitle": "Create and manage service records",
    "svc.newRecord": "New Service Record",
    "svc.editRecord": "Edit Service Record",
    "svc.selectCustomer": "Select Customer",
    "svc.clearSelection": "Clear Selection",
    "svc.searchCustomer": "Search customer...",
    "svc.addNewCustomer": "Add New Customer",
    "svc.customerName": "Customer Name",
    "svc.serviceAddress": "Service Address",
    "svc.startTime": "Start",
    "svc.endTime": "End",
    "svc.customerPhone": "Customer Phone",
    "svc.internalIp": "Internal IP",
    "svc.externalIp": "External IP",
    "svc.serviceServices": "Service Types",
    "svc.technicalServices": "Technical Services",
    "svc.details": "Details",
    "svc.serviceFee": "Service Fee (₺)",
    "svc.technician": "Technician",
    "svc.documentDate": "Document Date",
    "svc.update": "Update",
    "svc.save": "Save",
    "svc.allRecords": "All Service Records",
    "svc.showing": "records showing",
    "svc.filterAll": "All",
    "svc.filterDay": "Day",
    "svc.filterMonth": "Month",
    "svc.filterYear": "Year",
    "svc.filterDate": "Date",
    "svc.filterDocName": "Doc Name",
    "svc.filterCustomer": "Customer",
    "svc.colDate": "Date",
    "svc.colDocName": "Doc Name",
    "svc.colCustomer": "Customer",
    "svc.colService": "Service",
    "svc.colTemplate": "Template",
    "svc.allTemplates": "All Templates",
    "svc.noTemplate": "No Template",
    "svc.newCustomer": "New Customer",
    "svc.companyName": "Company Name",
    "svc.address": "Address",
    "svc.email": "Email",
    "svc.phone": "Phone",
    "svc.contactPerson": "Contact Person",
    "svc.contactPhone": "Contact Phone",
    "svc.cancel": "Cancel",
    "svc.customerSignature": "Customer Signature",
    "svc.confirmSave": "Are you sure you want to create this service record?",
    "svc.confirmUpdate": "Are you sure you want to update this service record?",
    "svc.confirmDelete": "Are you sure you want to delete \"{name}\" service record? This action cannot be undone.",
    "svc.delete": "Delete",
    "svc.signHere": "Please sign in this area",
    "svc.clear": "Clear",
    "svc.successCreated": "Service record created.",
    "svc.successUpdated": "Service record updated.",
    "svc.errorSave": "An error occurred while saving.",
    "svc.errorUpdate": "An error occurred while updating.",
    "svc.errorDelete": "Could not delete service record.",
    "svc.errorRequired": "Customer name is required.",
    "svc.errorTimeEqual": "Start and end time cannot be the same.",
    "svc.errorCompanyRequired": "Company name is required.",
    "svc.errorCustomerAdd": "An error occurred while adding customer.",
    "svc.noSignature": "To create or update a service record, please save your signature from the profile page.",
    "svc.warning": "Warning",
    "svc.error": "Error",
    "svc.success": "Success",
    "svc.share": "Share",
    "svc.shareTitle": "Service Record",
    "svc.shareOther": "Other",
    "svc.shareError": "An error occurred while sharing.",
    "svc.sharePhoneTitle": "Select Number",
    "svc.phoneService": "Service record phone",
    "svc.phoneMain": "Main phone",
    "svc.phoneContact": "Contact phone",
    "svc.phoneNotFound": "No phone number found for this record.",

    // Customers
    "cst.title": "Customer Management",
    "cst.subtitle": "View and manage your customers",
    "cst.newCustomer": "Add New Customer",
    "cst.editCustomer": "Edit Customer",
    "cst.allCustomers": "All Customers",
    "cst.records": "records",
    "cst.search": "Search customers...",
    "cst.noCustomers": "No customers found.",
    "cst.loading": "Loading...",
    "cst.previous": "Previous",
    "cst.next": "Next",
    "cst.customerInfo": "Customer Information",
    "cst.contactPerson": "Contact Person",
    "cst.phone": "Phone",
    "cst.contactPhone": "Contact Phone",
    "cst.fax": "Fax",
    "cst.website": "Website",
    "cst.email": "Email",
    "cst.address": "Address",
    "cst.edit": "Edit",
    "cst.close": "Close",
    "cst.companyName": "Company Name",
    "cst.subscriberNo": "Subscriber No",
    "cst.errorLoad": "An error occurred while loading customers.",
    "cst.errorRequired": "Company name is required",
    "cst.errorSave": "An error occurred while processing.",
    "cst.errorDelete": "An error occurred while deleting.",
    "cst.errorEdit": "An error occurred while loading customer data.",
    "cst.successAdd": "Customer added.",
    "cst.successUpdate": "Customer updated.",
    "cst.successDelete": "Customer deleted.",
    "cst.confirmDelete": "Are you sure you want to delete?",
    "cst.delete": "Delete",

    // Schedule
    "sch.title": "Schedule Management",
    "sch.subtitle": "Manage your teams and service schedules",
    "sch.day": "Day",
    "sch.week": "Week",
    "sch.month": "Month",
    "sch.allTeams": "All Teams",
    "sch.newPlan": "New Plan",
    "sch.planList": "Plan List",
    "sch.teams": "Teams",
    "sch.noTeams": "No teams available",
    "sch.newTeam": "New Team",
    "sch.noPlanToday": "No plans for today",
    "sch.noPlanWeek": "No plans for this week",
    "sch.noPlanMonth": "No plans for this month",
    "sch.noPlanFound": "No plans found",
    "sch.past": "Past",
    "sch.teamName": "Team Name",
    "sch.teamLeader": "Team Leader",
    "sch.selectLeader": "Select leader...",
    "sch.personnel": "Personnel",
    "sch.selectPersonnel": "Select personnel...",
    "sch.personnelSelected": "personnel selected",
    "sch.cancel": "Cancel",
    "sch.add": "Add",
    "sch.assignments": "assignments",
    "sch.personnelCount": "Personnel",
    "sch.teamDelete": "Delete Team",
    "sch.teamDeleteMsg": "Are you sure you want to delete this team? This action cannot be undone.",
    "sch.yesDelete": "Yes, Delete",
    "sch.addPersonnel": "Add Personnel",
    "sch.searchPersonnel": "Search personnel...",
    "sch.noResults": "No results found",
    "sch.noPersonnelLeft": "No personnel available to add",
    "sch.removePersonnel": "Remove Personnel",
    "sch.removePersonnelMsg": "Select the personnel you want to remove:",
    "sch.leaderWarning": "Leader: {leader} — leader cannot be removed, only members can be selected.",
    "sch.noPersonnelToRemove": "No personnel to remove in this team",
    "sch.removeSelected": "Remove Selected",
    "sch.removeDefault": "Remove Selected",
    "sch.newAppointment": "Service Assignment",
    "sch.updateAppointment": "Update Plan",
    "sch.customer": "Customer",
    "sch.selectCustomer": "Select customer...",
    "sch.date": "Date",
    "sch.time": "Time",
    "sch.duration": "Duration",
    "sch.selectTeam": "Select Team",
    "sch.serviceType": "Service Type",
    "sch.notes": "Notes",
    "sch.notesPlaceholder": "Service notes...",
    "sch.assign": "Assign",
    "sch.update": "Update",
    "sch.save": "Save",
    "sch.planDelete": "Delete Plan",
    "sch.planDeleteMsg": "Are you sure you want to delete this plan?",
    "sch.planDetail": "Plan Detail",
    "sch.timeDuration": "Time & Duration",
    "sch.team": "Team",
    "sch.loading": "Loading...",
    "sch.errorTeamRequired": "Team name and leader are required.",
    "sch.errorTeamAdd": "Could not add team.",
    "sch.errorTeamDelete": "Could not delete team.",
    "sch.errorPersonnelAdd": "Could not add personnel.",
    "sch.errorPersonnelRemove": "Could not remove personnel.",
    "sch.errorCustomerRequired": "Customer selection is required.",
    "sch.errorInvalidTime": "Enter a valid time (HH:MM).",
    "sch.errorTimeRange": "Time must be between 08:00 - 23:00.",
    "sch.errorConflict": "Conflict",
    "sch.errorConflictMsg": "\"{name}\" plan is already defined for this team between {time} - {duration}. Choose a different time.",
    "sch.errorSave": "Operation failed.",
    "sch.errorDrag": "Could not move plan.",
    "sch.errorLoad": "An error occurred while loading data.",
    "sch.errorSelectPersonnel": "Please select at least one personnel.",
    "sch.tempCustomer": "Enter temporary customer name...",
    "sch.selectPersonnelToRemove": "Select personnel",
    "sch.more": "more",

    // Profile
    "prf.title": "Profile",
    "prf.info": "Info",
    "prf.name": "Full Name",
    "prf.email": "Email",
    "prf.phone": "Phone",
    "prf.role": "Role",
    "prf.signature": "Signature",
    "prf.addSignature": "Click to Add Signature",
    "prf.mySignature": "My Signature",
    "prf.signHere": "Please sign in this area",
    "prf.clear": "Clear",
    "prf.save": "Save",
    "prf.adminPrivileges": "Admin Privileges",
    "prf.companyInfo": "Company Information",
    "prf.invitationCode": "Invitation Code",
    "prf.invitationHint": "Share this code to register employees.",
    "prf.address": "Address",
    "prf.companyPhone": "Phone",
    "prf.companyEmail": "Email",
    "prf.companyFax": "Fax",
    "prf.companyWebsite": "Website",
    "prf.taxNumber": "Tax Number",
    "prf.logo": "Logo",
    "prf.logoSelected": "Logo selected",
    "prf.logoSelect": "Select logo...",
    "prf.stamp": "Stamp",
    "prf.stampSelected": "Stamp selected",
    "prf.stampSelect": "Select stamp image...",
    "prf.logout": "Log Out",
    "prf.deleteAccount": "Delete Account",
    "prf.deleteAccountConfirm": "Are you sure you want to delete your account? This action cannot be undone.",
    "prf.errorDeleteAccount": "An error occurred while deleting the account.",
    "prf.loading": "Loading...",
    "prf.error": "An error occurred",
    "prf.retry": "Try Again",
    "prf.nameEmpty": "Full name cannot be empty.",
    "prf.companyNameEmpty": "Company name cannot be empty.",
    "prf.successUser": "Profile information updated.",
    "prf.successCompany": "Company information updated.",
    "prf.successSignature": "Your signature has been saved.",
    "prf.errorUser": "Update failed.",
    "prf.errorCompany": "Update failed.",
    "prf.errorSignature": "Could not save signature.",
    "prf.copied": "Copied",
    "prf.copiedMsg": "Invitation code copied to clipboard:\n{code}",
    "prf.signRequired": "Please provide a signature.",

    // Settings
    "set.title": "Settings",
    "set.subtitle": "Configure your profile and app settings",
    "set.platform": "Service Tracking Platform",
    "set.profileInfo": "Profile Information",
    "set.language": "Language",
    "set.turkish": "Türkçe",
    "set.english": "English",
    "set.privacy": "Privacy",
    "set.help": "Help",
    "set.version": "Version",
    "set.logout": "Log Out",

    // Service form templates
    "tpl.menuLabel": "Service Form Templates",
    "tpl.menuRight": "Edit",
    "tpl.title": "Service Form Templates",
    "tpl.subtitle": "Customize the service record form layout",
    "tpl.formLabel": "Form Template",
    "tpl.manage": "Manage",
    "tpl.create": "New Template",
    "tpl.createTitle": "Create New Template",
    "tpl.createSource": "Template content",
    "tpl.createCopy": "Copy from selected template",
    "tpl.createBlank": "Start from default (blank) template",
    "tpl.newTemplateName": "New Template",
    "tpl.created": "Template Created",
    "tpl.createdMsg": "New template created. You can edit and save it.",
    "tpl.saved": "Template saved.",
    "tpl.applyTitle": "Apply to Records",
    "tpl.applyMessage": "{count} records were saved with this template. Should the changes also be applied to their PDFs?",
    "tpl.applyYes": "Yes, Apply",
    "tpl.applyNo": "No",
    "tpl.applyCancel": "Cancel",
    "tpl.operationCancelled": "Operation canceled. Template was reverted to its previous state.",
    "tpl.recordsUpdated": "{count} records updated.",
    "tpl.errorApply": "Failed to apply to records.",
    "tpl.name": "Template Name",
    "tpl.namePlaceholder": "Enter template name",
    "tpl.setDefault": "Set as Default",
    "tpl.discard": "Discard Changes",
    "tpl.fieldsSection": "Form Fields",
    "tpl.fieldsHint": "Enable/disable fields, reorder them or rename labels.",
    "tpl.groupsSection": "Option Groups",
    "tpl.groupsHint": "Add, edit or remove groups and options.",
    "tpl.addOption": "Add Option",
    "tpl.addGroup": "Add Group",
    "tpl.editLabel": "Edit Label",
    "tpl.labelTr": "Turkish Label",
    "tpl.labelEn": "English Label",
    "tpl.label": "Label",
    "tpl.autoTranslateHint": "The other language will be auto-translated.",
    "tpl.confirmDelete": "Are you sure you want to delete this template?",
    "tpl.noAccess": "Admin access is required to view this page.",
    "tpl.newGroupTr": "Yeni Grup",
    "tpl.newGroupEn": "New Group",
    "tpl.newOptionTr": "Yeni Seçenek",
    "tpl.newOptionEn": "New Option",
    "tpl.errorSave": "Could not save template.",
    "tpl.errorDelete": "Could not delete template.",
    "tpl.errorDefault": "Could not set default template.",
    "tpl.addField": "Add Field",
    "tpl.newFieldTr": "Yeni Alan",
    "tpl.newFieldEn": "New Field",
    "tpl.inputType": "Input Type",
    "tpl.fieldOptions": "Options",
    "tpl.typeText": "Text",
    "tpl.typeNumber": "Number",
    "tpl.typeTextarea": "Multiline",
    "tpl.typeSelect": "Select",
    "tpl.typeRadio": "Radio",
    "tpl.typeMulti": "Multi Select",

    // Login
    "login.subtitle": "Service Tracking Platform",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgotPassword": "Forgot Password",
    "login.login": "Log In",
    "login.noAccount": "Don't have an account? ",
    "login.register": "Sign Up",
    "login.errorEmail": "Email cannot be empty.",
    "login.errorPassword": "Password cannot be empty.",
    "login.errorLogin": "Login failed. Please check your credentials.",
    "login.error": "Error",

    // Forgot Password
    "forgot.subtitle": "Forgot Password",
    "forgot.description": "Enter your email address and we'll send you a password reset code.",
    "forgot.email": "Email",
    "forgot.sendCode": "Send Code",
    "forgot.backToLogin": "Back to Login",
    "forgot.successTitle": "Code Sent",
    "forgot.successMessage": "Password reset code has been sent to your email.",
    "forgot.errorEmail": "Email cannot be empty.",
    "forgot.errorGeneric": "An error occurred while requesting password reset.",

    // Reset Password
    "reset.title": "Reset Password",
    "reset.subtitle": "Enter the 6-digit code sent to your email and your new password",
    "reset.emailSent": "Reset code sent to {email}",
    "reset.newPassword": "New Password",
    "reset.confirmPassword": "Confirm Password",
    "reset.resetButton": "Reset Password",
    "reset.success": "Your password has been successfully reset!",
    "reset.errorEmptyCode": "Verification code cannot be empty.",
    "reset.errorEmptyPassword": "New password cannot be empty.",
    "reset.errorPasswordLength": "Password must be at least 6 characters.",
    "reset.errorPasswordMatch": "Passwords do not match.",
    "reset.errorGeneric": "An error occurred during password reset.",

    // Common
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.ok": "OK",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.service": "Service",

    // Privacy
    "privacy.title": "Privacy Policy",
    "privacy.dataStorage": "Data Storage & Security",
    "privacy.dataStorageDesc": "Your data is stored with SSL encryption. Our servers are hosted in Turkey. Regular security audits are performed.",
    "privacy.personalData": "Personal Data Usage",
    "privacy.personalDataDesc": "Your name, surname, email, and phone information are used only for service management. Your signature data is used only in service forms. Data is not shared with third parties.",
    "privacy.dataSharing": "Data Sharing",
    "privacy.dataSharingDesc": "Your customer information can only be viewed by authorized personnel. Your data is not shared unless legally required.",
    "privacy.retention": "Data Retention",
    "privacy.retentionDesc": "Your data is retained as long as your account is active. When an account is deleted, all data is permanently deleted within 30 days.",
    "privacy.accountDeletion": "Account Deletion",
    "privacy.accountDeletionDesc": "To delete your account, you can log out from the Settings menu or contact our support team. This action cannot be undone.",
    "privacy.notifications": "Communication Preferences",
    "privacy.notificationsDesc": "You can adjust your notification preferences. You can opt out of marketing emails.",
    "privacy.contact": "For privacy-related questions, please contact us.",
    "privacy.email": "privacy@company.com",

    // Month names
    "month.january": "January",
    "month.february": "February",
    "month.march": "March",
    "month.april": "April",
    "month.may": "May",
    "month.june": "June",
    "month.july": "July",
    "month.august": "August",
    "month.september": "September",
    "month.october": "October",
    "month.november": "November",
    "month.december": "December",

    // Day names
    "day.monday": "Monday",
    "day.tuesday": "Tuesday",
    "day.wednesday": "Wednesday",
    "day.thursday": "Thursday",
    "day.friday": "Friday",
    "day.saturday": "Saturday",
    "day.sunday": "Sunday",

    // Duration
    "dur.30min": "30 min",
    "dur.1hour": "1 hour",
    "dur.1.5hour": "1.5 hours",
    "dur.2hour": "2 hours",
    "dur.custom": "Custom (hours)",

    // Days short
    "dayShort.mon": "Mon",
    "dayShort.tue": "Tue",
    "dayShort.wed": "Wed",
    "dayShort.thu": "Thu",
    "dayShort.fri": "Fri",
    "dayShort.sat": "Sat",
    "dayShort.sun": "Sun",

    // Service lists
    "svc.list.alarm": "Alarm",
    "svc.list.fire": "Fire",
    "svc.list.cctv": "CCTV",
    "svc.list.ahm": "AHM Connection",
    "svc.list.wiring": "Wiring",
    "svc.list.assembly": "Assembly",
    "svc.list.commissioning": "Commissioning Training",
    "svc.list.docCheck": "Document Check",
    "svc.list.testing": "Test Signal Programming",
    "svc.list.maintenance": "Maintenance",
    "svc.list.repair": "Repair",
    "svc.list.training": "Commissioning",

    // Technical list
    "svc.tech.ahmSignal": "AHM Signal Check",
    "svc.tech.drill": "Training and Drill",
    "svc.tech.dovr": "DOVR Record Check",
    "svc.tech.remote": "Remote Access",
    "svc.tech.backup": "Recording and Backup Training",
    "svc.tech.cameraClarity": "Camera Clarity and Direction Adjustment",
    "svc.tech.signalTest": "Test Signal Programming",
    "svc.tech.battery": "Battery Life Check",
    "svc.tech.wirelessPil": "Wireless Detector Battery Check",
    "svc.tech.gprs": "GPRS Connection",

    // Service form extras
    "svc.serviceForm": "Service Form",
    "svc.serviceInfo": "Service Information",
    "svc.feeLabel": "Fee:",
    "svc.technical": "Technical:",
    "svc.services": "Services:",
    "svc.notSpecified": "Not specified",
    "svc.confirmCreate": "Are you sure you want to create this service record?",
    "svc.signatureRequired": "Signature Required",
    "svc.signatureWarning": "Please provide a signature.",
    "svc.goToProfile": "Go to Profile Page",
    "svc.pdfDialogTitle": "Service Form.pdf",
    "svc.errorPdfData": "PDF data not found.",
    "svc.errorPopup": "Could not open new window. Please check pop-up blocker.",
    "svc.errorPdfCreate": "An error occurred while creating PDF: ",
    "svc.infoPdf": "PDF creation feature is being redesigned...",
    "svc.downloadPdf": "Download PDF",
    "svc.companyNamePlaceholder": "Company name",
    "svc.subscriberNo": "Subscriber No",
    "svc.customerNamePlaceholder": "Enter customer name",
    "svc.serviceAddressPlaceholder": "Enter or select service address",
    "svc.phonePlaceholder": "Phone number",
    "svc.contactPersonPlaceholder": "Contact person",
    "svc.contactPhonePlaceholder": "Contact phone",
    "svc.internalIpPlaceholder": "Internal IP",
    "svc.externalIpPlaceholder": "External IP",
    "svc.detailsPlaceholder": "Additional details or notes",
    "svc.datePlaceholder": "Enter date (DD/MM/YYYY)",
    "svc.documentName": "Document Name",

    // Dashboard extras
    "dash.service": "Service",
    "dash.paid": "Paid",
    "dash.pending": "Pending",

    // Schedule extras
    "sch.servicePlan": "service plan",
    "sch.leader": "Leader:",
    "sch.serviceTypes.alarm": "Alarm",
    "sch.serviceTypes.fire": "Fire",
    "sch.serviceTypes.cctv": "CCTV",
    "sch.serviceTypes.assembly": "Assembly",
    "sch.serviceTypes.wiring": "Wiring",
    "sch.serviceTypes.commissioning": "Commissioning",
    "sch.serviceTypes.maintenance": "Maintenance",
    "sch.serviceTypes.repair": "Repair",

    // Register
    "reg.title": "Create a new account",
    "reg.inviteCode": "Invite Code",
    "reg.inviteCodePlaceholder": "Enter admin or invite code",
    "reg.inviteHint": "Use \"ADMIN-XXX\" for admin, \"INVITE-XXX\" to register employees.",
    "reg.fullName": "Full Name",
    "reg.email": "Email",
    "reg.phone": "Phone",
    "reg.password": "Password",
    "reg.confirmPassword": "Confirm Password",
    "reg.register": "Sign Up",
    "reg.hasAccount": "Already have an account? ",
    "reg.login": "Log In",
    "reg.errorInviteCode": "Invite code cannot be empty.",
    "reg.errorName": "Name field cannot be empty.",
    "reg.errorEmail": "Enter a valid email address.",
    "reg.errorPhone": "Phone must be at least 10 digits.",
    "reg.errorPassword": "Password must be at least 6 characters.",
    "reg.errorPasswordMatch": "Passwords do not match.",
    "reg.errorRegister": "Registration failed. Please try again.",

    // Email Verification
    "verify.title": "Email Verification",
    "verify.subtitle": "Enter the 6-digit verification code sent to your email",
    "verify.emailSent": "Verification code sent to {email}",
    "verify.codePlaceholder": "Verification Code",
    "verify.verify": "Verify",
    "verify.resend": "Resend Code",
    "verify.resendIn": "You can resend in {seconds} seconds",
    "verify.success": "Email verified successfully!",
    "verify.errorEmpty": "Verification code cannot be empty.",
    "verify.errorInvalid": "Invalid verification code.",
    "verify.errorExpired": "Verification code has expired. Please request a new one.",
    "verify.errorGeneric": "An error occurred during verification.",
    "verify.backToLogin": "Back to Login",
    "verify.pasteCode": "Paste Code",
    "verify.codeCopied": "Code copied to clipboard!",

    // Complete CP Profile
    "cp.title": "Complete Corporate Information",
    "cp.subtitle": "Complete your account by entering company information",
    "cp.logo": "Logo",
    "cp.logoHint": "Click on the logo to change",
    "cp.companyName": "Company Name",
    "cp.companyNamePlaceholder": "Company name",
    "cp.address": "Address",
    "cp.companyAddressPlaceholder": "Company address",
    "cp.phone": "Phone",
    "cp.taxNumber": "Tax Number",
    "cp.email": "Email",
    "cp.complete": "Complete",
    "cp.errorGeneric": "A problem occurred. Please try again.",

    // MapSelector
    "map.selectAddress": "Select Address",
    "map.currentLocation": "Get My Current Location",
    "map.gpsHint": "Use your location with GPS",
    "map.selectFromMap": "Select from Map",
    "map.googleMapsHint": "Set address in Google Maps",
    "map.mapHint": "Select a point on the map",
    "map.permissionRequired": "Permission Required",
    "map.permissionDenied": "Location permission not granted.",
    "map.errorLocation": "Location could not be obtained. Check browser location permission.",
    "map.errorLocationMobile": "Location could not be obtained. Please check GPS and internet connection.",

    // PDF
    "pdf.title": "SERVICE DELIVERY FORM",
    "pdf.date": "Date:",
    "pdf.customerInfo": "CUSTOMER INFORMATION",
    "pdf.customerName": "Customer Name:",
    "pdf.address": "Address:",
    "pdf.phone": "Phone:",
    "pdf.email": "Email:",
    "pdf.subscriberNo": "Subscriber No:",
    "pdf.serviceDetails": "SERVICE DETAILS",
    "pdf.responsiblePersonnel": "Responsible Personnel:",
    "pdf.startTime": "Start Time:",
    "pdf.endTime": "End Time:",
    "pdf.phoneNumber": "Phone Number:",
    "pdf.serviceServices": "SERVICE TYPES",
    "pdf.technicalServices": "TECHNICAL SERVICES",
    "pdf.detailsNotes": "DETAILS / NOTES",
    "pdf.additionalInfo": "ADDITIONAL INFO",
    "pdf.serviceFee": "SERVICE FEE",
    "pdf.serviceFeeLine": "Service Fee: {amount} + VAT",
    "pdf.freeService": "Free Service",
    "pdf.customerSignatureLabel": "Customer Name & Surname / Signature",
    "pdf.technicianSignatureLabel": "Technician Name & Surname / Signature",
    "pdf.companyNameLabel": "1D SECURITY AND COMMUNICATION SYSTEMS TRADE LTD.",
    "pdf.companyAddressLabel": "Goncalar Mah. Ali Alp Böke Cad. No: 150 C Karşıyaka - IZMIR",
    "pdf.privacyNoteTitle": "PRIVACY NOTICE (KVKK)",
    "pdf.privacyNoteBody": "This document is confidential under Law No. 6698 (KVKK) and is intended solely for the relevant customer. Unauthorized disclosure is prohibited.",

    // Profile extra
    "prf.errorLoad": "Profile information could not be loaded.",

    // Auth extras
    "auth.errorToken": "Token could not be obtained. Please try again.",
    "auth.errorTokenSave": "Token could not be saved. Please try again.",
    "auth.errorRegisterToken": "Token could not be obtained after registration.",

    // Common extras
    "common.info": "Info",
    "common.all": "All",
    "common.day": "Day",
    "common.month": "Month",
    "common.year": "Year",
    "common.date": "Date",
    "common.customer": "Customer",
    "common.address": "Address",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.password": "Password",
    "common.clear": "Clear",
  },
};

interface LanguageContextType {
  lang: Lang;
  t: (key: string, params?: Record<string, string>) => string;
  setLanguage: (lang: Lang) => void;
  locale: string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "tr",
  t: (key) => key,
  setLanguage: () => {},
  locale: "tr-TR",
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("tr");

  useEffect(() => {
    AsyncStorage.getItem("language").then((v) => {
      if (v === "en" || v === "tr") setLangState(v);
    });
  }, []);

  const setLanguage = useCallback((l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem("language", l);
  }, []);

  const t = useCallback(
    (key: string, params?: Record<string, string>): string => {
      let text = translations[lang]?.[key] || translations.tr[key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          text = text.replace(new RegExp(`\\{${k}\\}`, "g"), v);
        });
      }
      return text;
    },
    [lang]
  );

  const locale = lang === "tr" ? "tr-TR" : "en-US";

  return (
    <LanguageContext.Provider value={{ lang, t, setLanguage, locale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
