ALTER TABLE "ServiceRecord" ADD COLUMN "labor" TEXT NOT NULL DEFAULT '0.00';
ALTER TABLE "ServiceRecord" ADD COLUMN "laborCurrency" TEXT NOT NULL DEFAULT 'TRY';
ALTER TABLE "ServiceRecord" ADD COLUMN "kdvRate" TEXT NOT NULL DEFAULT '20';